package com.businessnext.objects.lead.pages;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;

import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.Select;

import com.common.pages.CommonProductFunctions;
import com.drivermanager.DriverManager;
import com.utilities.ReUsableMethods;

public class LeadCreationPageWithCustomField {

	WebDriver wdriver;

	public LeadCreationPageWithCustomField(WebDriver driver) {
		this.wdriver = driver;
		PageFactory.initElements(wdriver, this);
	}

	// Enter Lead_Name Initialization

	@FindBy(xpath = "//span[@title='Cus_Autogenerated']")
	public WebElement autogeneratedTab;

	@FindBy(xpath = "//label[@for='chk_2']")
	public WebElement booleanCheckbox;

	@FindBy(xpath = "//input[@data-autoid='LE_COUNTRY_ctrl']")
	public WebElement country;

	@FindBy(xpath = "//input[@data-autoid='LE_STATE_ctrl']")
	public WebElement state;

	@FindBy(xpath = "//*[@data-cke-tooltip-text='Enter fullscreen mode']")
	public WebElement expandHtml;

	@FindBy(xpath = "//*[@data-cke-tooltip-text='Leave fullscreen mode']")
	public WebElement collapseHtml;

	@FindBy(xpath = "//div[@role='textbox']/parent::*[@class='ck ck-fullscreen__editable']")
	public WebElement textboxHtml;

	@FindBy(xpath = "//input[@data-autoid='LE_CITY_ctrl']")
	public WebElement city;

	@FindBy(xpath = "//input[@data-autoid='LE_ZIP_CODE_ctrl']")
	public WebElement pinCode;

	@FindBy(xpath = "(//label[@title='Aut_Rating']/following::img)[1]")
	public WebElement autRating;

	@FindBy(xpath = "//label[@title='Value']/ancestor::div[contains(@data-autoid,'cont')]//textarea")
	public WebElement valueMassUpdate;

	@FindBy(xpath = "//label[@title='Aut_Percentage']/ancestor::div[contains(@data-autoid,'cust_')]//input")
	public WebElement percentageOnNumericTab;

	@FindBy(xpath = "//div[@class='longtextmessage']")
	public WebElement warningMessageDate;

	@FindBy(xpath = "//label[@title='Aut_NonEditpick']/ancestor::div[contains(@data-autoid,'cust')]//div/input")
	public WebElement nonEditPickerOnNewEdit;

	@FindBy(xpath = "//label[@title='Aut_testfield']/ancestor::div[contains(@data-autoid,'cust')]//input[@title=\"DD/MM/YYYY\"]")
	public WebElement aut_testField;

	@FindBy(xpath = "//label[@title='Enddate']/ancestor::div[contains(@data-autoid,'cust')]//input[@title=\"DD/MM/YYYY\"]")
	public WebElement endDate;

	@FindBy(xpath = "//label[@title='Auto_temp_text']/parent::div//div[@role='textbox']")
	public WebElement text_NormalPicker;

	@FindBy(xpath = "//span[@data-testid='validation-label']")
	public WebElement validationMessage;

	@FindBy(xpath = " //div[@data-autoid='Pck_SearchDropDown_ctrl']")
	public WebElement selectTag;

	@FindBy(xpath = "//label[@title='Auto_Temp_HTML']/parent::div//div[@role='textbox']")
	public WebElement html_NormalPicker;

	@FindBy(xpath = "//label[@title='NormalPicker_Lookup_SpecialCharacter']/parent::div//select")
	public WebElement normalPicker_Lookup_SpecialCharacter;

	@FindBy(xpath = "//div[@data-testid=\"dialog-alert-icon\"]//following::p")
	public WebElement normalPicker_Lookup_SpecialCharacter_Message;

	@FindBy(xpath = "//label[@title = 'Aut_Text']//parent::div//input")
	public WebElement aut_textBox;

	public String get_NormalPicker_Lookup_SpecialCharacter_Message() {
		return ReUsableMethods.WebGetElementText(normalPicker_Lookup_SpecialCharacter_Message,
				"NormalPicker Lookup SpecialCharacter Message");
	}

	public void select_normalPicker_Lookup_SpecialCharacter(String value) {
		ReUsableMethods.webSelectByVisibleText(normalPicker_Lookup_SpecialCharacter, value,
				"Normal lookup special character");

	}

	public String getWarningMessageDate() {
		return ReUsableMethods.WebGetElementText(warningMessageDate, "Warning Message Date");
	}

	public void clickOnAutogeneratedTab() {
		ReUsableMethods.webClickElement(autogeneratedTab, "Autogenerated Tab");
	}

	public void clickOnCollapse() {
		ReUsableMethods.webClickElement(collapseHtml, "Collapse Html");
	}

	public void clickOnExpand() {
		ReUsableMethods.webClickElement(expandHtml, "Expand Html");
	}

	public String getvalidationMessage() {
		return ReUsableMethods.WebGetElementText(validationMessage, "Validation Message");
	}

	public String getNonEditPickerOnNewEdit() throws Exception {
		return ReUsableMethods.getTextElementAttribute(nonEditPickerOnNewEdit, "value");
	}

	public String createLeadCustomField(String LAYOUT, String FIRSTNAME, String LASTNAME, String RATING, String PRODUCT)
			throws Exception {

		LeadCreationPage leadCreationPage = new LeadCreationPage(DriverManager.getWdriver());
		CommonProductFunctions commonProductFunctions = new CommonProductFunctions(DriverManager.getWdriver());
		LeadHomePage leadHomePage = new LeadHomePage(DriverManager.getWdriver());

		ReUsableMethods.webClickElement(leadHomePage.newIcon, "New Icon");
		commonProductFunctions.clickOnLayout(LAYOUT);
		ReUsableMethods.webEnterText(leadCreationPage.leadFirstName, FIRSTNAME, "Lead First Name");
		String expectedLastname = leadCreationPage.enterLastName(LASTNAME);

		leadCreationPage.selectLeadRating(RATING);

		leadCreationPage.selectLeadProduct(PRODUCT);

		return expectedLastname;

	}

	String preButton = "//label[@title='";
	String postButton = "']/parent::div//i[@class='icon icon-acid-search']";

	public void clickOnSearchPicker(String picker) throws InterruptedException {

		String xpath = preButton + picker + postButton;
		List<WebElement> ele = ReUsableMethods.findElementByPath(xpath);
		ReUsableMethods.scrollElementToCentreOfScreen(ele.get(0));
		ReUsableMethods.webClickElement(ele.get(0), picker);

	}

	// div[text()='15 character(s) remaining.']"

	String preRemainingButton = "//div[text()='";
	String postRemainingButton = " character(s) remaining.']";

	public boolean remainingCharacterField(String number) throws InterruptedException {

		String xpath = preRemainingButton + number + postRemainingButton;
		List<WebElement> ele = ReUsableMethods.findElementByPath(xpath);
		ReUsableMethods.scrollElementToCentreOfScreen(ele.get(0));
		return ReUsableMethods.WebIsElementDisplayed(ele.get(0), number);

	}

	// label[@title='Aut_Comment']/ancestor::div[contains(@data-autoid,'cust_')]//textarea

	String preLongTextButton = "//label[@title='";
	String postLongTextButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//textarea";

	public void enterLongTextFields(String fieldtitle, String text) throws InterruptedException {

		String xpath = preLongTextButton + fieldtitle + postLongTextButton;
		WebElement ele = ReUsableMethods.findElementByPath(xpath).get(0);
		ReUsableMethods.scrollElementToCentreOfScreen(ele);
		ReUsableMethods.webClearText(ele, fieldtitle);
		ReUsableMethods.webEnterText(ele, text, fieldtitle);

	}

	public void enterTextOnPercentage(String text) {
		ReUsableMethods.webClearText(percentageOnNumericTab, "PercentageInput");
		ReUsableMethods.webEnterText(percentageOnNumericTab, text, "Percentage");
	}

	String postTextButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//input";
	String preXpathForCustomDataField = "//label[@title='";

	public void enterTextFields(String fieldtitle, String text) throws InterruptedException {

		String xpath = preLongTextButton + fieldtitle + postTextButton;
		WebElement ele = ReUsableMethods.findElementByPath(xpath).get(0);
		ReUsableMethods.scrollElementToCentreOfScreen(ele);
		ReUsableMethods.selectAllAndBackspaceToClear(ele);
		// ReUsableMethods.webClearText(ele, fieldtitle);
		ReUsableMethods.webEnterText(ele, text, fieldtitle);

	}

	String preDateTimeButton = "//label[@title='";
	String postDateButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//input[@title='DD/MM/YYYY']";
	String postTimeButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//input[@placeholder='__:__']";

	public void enterDateTimeCustomField(String fieldtitle, String date, String time) throws InterruptedException {

		String xpath = preDateTimeButton + fieldtitle + postDateButton;
		WebElement ele = ReUsableMethods.findElementByPath(xpath).get(0);
		ReUsableMethods.scrollElementToCentreOfScreen(ele);
		ReUsableMethods.webClearText(ele, xpath);
		ReUsableMethods.webEnterText(ele, date, fieldtitle);
		if (date == "") {
			clickOnTodayDate(fieldtitle);
		}

		String xpathTime = preDateTimeButton + fieldtitle + postTimeButton;
		WebElement element = ReUsableMethods.findElementByPath(xpathTime).get(0);
		ReUsableMethods.webClearText(element, xpathTime);
		ReUsableMethods.webEnterText(element, time, fieldtitle);

	}

	String postDateTimeButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//span";

	public String getDateTimeCustomField(String title) throws InterruptedException {

		String xpath = preDateTimeButton + title + postDateTimeButton;
		List<WebElement> ele = ReUsableMethods.findElementByPath(xpath);
		ReUsableMethods.scrollElementToCentreOfScreen(ele.get(0));
		return ReUsableMethods.WebGetElementText(ele.get(0), "title");

	}

	String postTodatDateButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//div[@title=\"Today's date\"]";

	public void clickOnTodayDate(String fieldtitle) throws InterruptedException {

		String xpath = preLongTextButton + fieldtitle + postTodatDateButton;
		WebElement ele = ReUsableMethods.findElementByPath(xpath).get(0);
		ReUsableMethods.scrollElementToCentreOfScreen(ele);
		ReUsableMethods.webClickElement(ele, fieldtitle);

	}

	// to get currentDate

	public HashMap<String, String> getStartEndDate(long years, long months, long days) {
		HashMap<String, String> map = new HashMap<>();

		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

		// Current date
		LocalDate endDate = LocalDate.now();

		// Subtract years, months, and days
		LocalDate startDate = endDate.minusYears(years).minusMonths(months).minusDays(days);

		// Format the dates
		String startDateStr = startDate.format(formatter);
		String endDateStr = endDate.format(formatter);

		map.put("StartDate", startDateStr);
		map.put("EndDate", endDateStr);

		return map;
	}

	String preDateButton = "(//label[@title='";
	String postMonthButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//select)[1]";
	String postDayButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//select)[2]";
	String postYearButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//select)[3]";

	public void selectDateInCustomField(String title, String day, String month, String year) {

		String fieldXpath = "//label[normalize-space(text())='" + title + "']" + "/following-sibling::div//select";

		List<WebElement> dateSelects = ReUsableMethods.findElementByPath(fieldXpath);

		WebElement daySelect = null;
		WebElement monthSelect = null;
		WebElement yearSelect = null;

		// Only 3 elements – scoped to this field
		for (WebElement select : dateSelects) {

			String firstOption = new Select(select).getOptions().get(0).getText().trim();

			if ("DD".equals(firstOption)) {
				daySelect = select;
			} else if ("MM".equals(firstOption)) {
				monthSelect = select;
			} else if ("YYYY".equals(firstOption)) {
				yearSelect = select;
			}
		}

		if (daySelect != null && day != null && !day.isEmpty()) {
			ReUsableMethods.scrollElementToCentreOfScreen(daySelect);
			new Select(daySelect).selectByVisibleText(day);
		}

		if (monthSelect != null && month != null && !month.isEmpty()) {
			month = month.startsWith("0") ? month.substring(1) : month;
			ReUsableMethods.scrollElementToCentreOfScreen(monthSelect);
			try {
				new Select(monthSelect).selectByVisibleText(month);
			} catch (Exception e) {
				new Select(monthSelect).selectByValue(month);
			}
		}

		if (yearSelect != null && year != null && !year.isEmpty()) {
			ReUsableMethods.scrollElementToCentreOfScreen(yearSelect);
			new Select(yearSelect).selectByVisibleText(year);
		}
	}

	String postSelectButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//select";

	public void selectDropDownCustomField(String title, String field) throws InterruptedException {
		String xpath = preLongTextButton + title + postSelectButton;
		WebElement ele = ReUsableMethods.findElementByPath(xpath).get(0);
		ReUsableMethods.scrollElementToCentreOfScreen(ele);
		ReUsableMethods.webSelectByVisibleText(ele, field, title);

	}

	public boolean clickOnCheckboxOrText(String title, String field, String action) {
		String xpath = String.format("//label[@title='%s']//following::*[text()='%s']", title, field);
		List<WebElement> list = ReUsableMethods.findElementByPath(xpath);
		ReUsableMethods.scrollElementToCentreOfScreen(list.get(0));
		if (action.equalsIgnoreCase("Click")) {
			ReUsableMethods.webClickElement(list.get(0), title);

		}

		else if (action.equalsIgnoreCase("Verify")) {

			return ReUsableMethods.isWebElementDisplayed(list);

		}

		return false;
	}

	@FindBy(xpath = "//input[@data-autoid='cust_1324_ctrl']")
	public WebElement aut_DateSet;

	public void setDateInAut_DateSetField(int daysToAdd) {

		LocalDate targetDate = LocalDate.now().plusDays(daysToAdd);

		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
		String formattedDate = targetDate.format(formatter);
		ReUsableMethods.webClearText(aut_DateSet, "aut_DateSet");
		ReUsableMethods.webEnterText(aut_DateSet, formattedDate, formattedDate);

	}

	// label[@title='Aut_time']/ancestor::div[contains(@data-autoid,'cust_')]//i
	String postSelectTimeButton = "']/ancestor::div[contains(@data-autoid,'cust_')]//i";

	@FindBy(xpath = "//input[@data-autoid='cust_973_ctrl']")
	public WebElement aut_text;

	public void enterDataInAut_text(String data) {
		ReUsableMethods.webClearText(aut_text, "aut_text");
		ReUsableMethods.webEnterText(aut_text, data, "aut_text");
	}

	public void clickOnTimeCustomField(String title) throws InterruptedException {
		String xpath = preLongTextButton + title + postSelectTimeButton;
		WebElement ele = ReUsableMethods.findElementByPath(xpath).get(0);
		ReUsableMethods.scrollElementToCentreOfScreen(ele);
		ReUsableMethods.webClickElement(ele, title);

	}

	String postTextBoxButton = "']/parent::div//div[@role='textbox']";

	public void enterTextInEditor(String fieldtitle, String text) throws InterruptedException {

		String xpath = preLongTextButton + fieldtitle + postTextBoxButton;
		WebElement ele = ReUsableMethods.findElementByPath(xpath).get(0);
		ReUsableMethods.scrollElementToCentreOfScreen(ele);
		ReUsableMethods.selectAllAndBackspaceToClear(ele);
		ReUsableMethods.webEnterText(ele, text, fieldtitle);

	}

	public void enterDataInCustomField(String fieldName, String data) {
		String xpath = preXpathForCustomDataField + fieldName + postTextButton;
		List<WebElement> ele = ReUsableMethods.findElementByPath(xpath);
		// ReUsableMethods.webClearText(ele.get(0), "clear");
		ReUsableMethods.selectAllAndBackspaceToClear(ele.get(0));
		ReUsableMethods.webEnterText(ele.get(0), data, "data");

	}

	// public void clickOnLongText_MentionOption(String text) {
	// String xpath =
	// String.format("//span[contains(@class,'mention-input__suggestions__item__display')][.='%s']",
	// text);
	// List<WebElement> list = ReUsableMethods.findElementByPath(xpath);
	// ReUsableMethods.scrollElementToCentreOfScreen(list.get(0));
	// ReUsableMethods.webClickElement(list.get(0), text);

	// }

	String postXpathFordDropDown = "']/ancestor::div[contains(@data-autoid,'cust_')]";

	public void DropDownCustomField(String title) throws InterruptedException {

		String xpath = String.format("//label[@title='%s']/parent::div//div//div[contains(@class,'countryContainer')]",
				title);
		List<WebElement> list = ReUsableMethods.findElementByPath(xpath);
		ReUsableMethods.scrollElementToCentreOfScreen(list.get(0));
		ReUsableMethods.webClickElement(list.get(0), title);

		// String xpath = preLongTextButton + title + postXpathFordDropDown;
		// WebElement ele = ReUsableMethods.findElementByPath(xpath).get(0);
		// ReUsableMethods.scrollElementToCentreOfScreen(ele);
		// ReUsableMethods.webClickElement(ele, title);

	}

	@FindBy(xpath = "//input[@placeholder='Search' and @type='text']")
	public WebElement searchBox;

	String preXpathForFlagName = "//span[text()='";
	String postXpathForFlagName = "']";

	public void clickOnFlagName(String flagName) throws InterruptedException {
		String xpath = preXpathForFlagName + flagName + postXpathForFlagName;
		WebElement ele = ReUsableMethods.findElementByPath(xpath).get(0);
		ReUsableMethods.scrollElementToCentreOfScreen(ele);
		ReUsableMethods.webClickElement(ele, flagName);

	}

	public void selectCountryFlagCustomFieldFromDropDown(String title, String searchFlag, String flagName)
			throws InterruptedException {
		DropDownCustomField(title);
		ReUsableMethods.webEnterText(searchBox, searchFlag, "Field Name");
		clickOnFlagName(flagName);
	}

	@FindBy(xpath = "//input[@type='checkbox']//following-sibling::label[@data-autoid='cust_987_lbl']")
	public WebElement booleanCheck;

	public void clickOnBooleanCheck() {
		ReUsableMethods.clickCheckBoxUsingJavaScript(booleanCheck);
	}

	public void enterTextboxHtmlAfterExpand(String text) {
	//	ReUsableMethods.selectAllAndBackspaceToClear(textboxHtml);
		Actions actions = new Actions(DriverManager.getWdriver());
		 actions.keyDown(Keys.CONTROL).sendKeys("a").keyUp(Keys.CONTROL).sendKeys(Keys.BACK_SPACE).perform();
		ReUsableMethods.typeString(text);
		// ReUsableMethods.webEnterText(textboxHtml, text, "HTML Textbox");

	}

	public void clickOn_MentionOption(String text) {
		String xpath = String.format("//button[contains(@class,'ck-button_with-text')]//span[text()='%s']", text);
		List<WebElement> list = ReUsableMethods.findElementByPath(xpath);
		ReUsableMethods.scrollElementToCentreOfScreen(list.get(0));
		ReUsableMethods.webClickElement(list.get(0), text);
	}

	public void clickOnLongText_MentionOption(String text) {
		String xpath = String.format("//span[contains(@class,'mention-input__suggestions__item__display')][.='%s']",
				text);
		List<WebElement> list = ReUsableMethods.findElementByPath(xpath);
		ReUsableMethods.scrollElementToCentreOfScreen(list.get(0));
		ReUsableMethods.webClickElement(list.get(0), text);

	}

	public void selectFirstValueFromPicker(String value) {

		String xpath = String.format(
				"//div[@title= '%s' and contains(@data-autoid,'')]//parent::div[contains(@class,'grid-cell')]",
				value);

		List<WebElement> list = ReUsableMethods.findElementByPath(xpath);

		WebElement ele = list.get(0);

		ReUsableMethods.webClickElement(ele, "title");

	}

	public void normalPickerFields(String multiPick, String customValue, boolean selectCheckbox) throws Exception {

		CommonProductFunctions commonProductFunctions = new CommonProductFunctions(DriverManager.getWdriver());

		commonProductFunctions.clickOnSearchPicker(multiPick);
		commonProductFunctions.searchApply(customValue);

		if (selectCheckbox) {
			commonProductFunctions.clickOnFirstCheckBox();
			ReUsableMethods.webClickElement(commonProductFunctions.okayButton, "OkButton");
		}

	}

	public void clickOnFieldValueCheckbox(String fieldName, String labelName) {
		String xpath = String.format("//label[@title = '%s']//parent::div//label[text()='%s']", fieldName, labelName);

		List<WebElement> list = ReUsableMethods.findElementByPath(xpath);

		WebElement ele = list.get(0);

		ReUsableMethods.webClickElement(ele, fieldName);
	}

	public void selectValueInMultiLevelCustomField(String fieldName, String dropDownValue) {
		String xpath = String.format("//label[@title = '%s']//parent::div//select", fieldName);

		List<WebElement> list = ReUsableMethods.findElementByPath(xpath);

		WebElement ele = list.get(0);

		ReUsableMethods.webSelectByVisibleText(ele, dropDownValue, "country");
	}

	public void clickAndSelectValueFromPicker(String fieldName, String searchByValue, String fieldValue)
			throws Exception {
		CommonProductFunctions commonProductFunctions = new CommonProductFunctions(DriverManager.getWdriver());
		commonProductFunctions.clickOnSearchPicker(fieldName);
		commonProductFunctions.selectSearchByvalueInPickerSearch(searchByValue);
		commonProductFunctions.searchApply(fieldValue);

	}

	public void clickOnDateTimeCustomFields(String fieldName) {
		String xpath = String.format("//label[@title = '%s']//parent::div//div[@title = \"Today's date\"]", fieldName);

		List<WebElement> list = ReUsableMethods.findElementByPath(xpath);

		WebElement ele = list.get(0);

		ReUsableMethods.webClickElement(ele, fieldName);

	}

}
